### ISSUE TITLE
Links in README don't work 

### ISSUE THREAD

**Issue by bstienen** [jakimfett/ParticlePhysics#28]
I would love to read in on this package, but some of the links in the README are not working anymore, including the documentation link http://jakimfett.com/minecraft/particle-physics/.

**Comment by jakimfett** [comment]
Thanks for alerting me, @bstienen .
Should be fixed now, want to give it a try?

(feel free to re-open the issue if that didn't work for you.)

**Comment by bstienen** [comment]
Thanks for updating!
The only link that still does not work is http://jenkins.jakimfett.com/job/ParticlePhysics/ (the link to the most recent build). Same is true for this link in http://jakimfett.com/status-report/splitting-minechem/ btw. As I think I can just build it myself, its not a problem for me, but strictly speaking it is still something that does not work.

**Comment by jakimfett** [comment]
Yup, the build system is still offline, ish.

> brief backstory:
> After I [quit Minecraft modding](https://jakimfett.com/status-report/epilogue-modding-minecraft/), I got harassed out of my day job, and then my startup got stolen by fascists.  
> Then I spent a year or three dealing with the fallout of a doctor's malpractice soaking my brain in literal poison.  
> 
> Since then, most of my infrastructure (including the server rack, blade server cluster, and networking gear) that used to handle all this, is wrapped in plastic in a warehouse gathering dust.
> Got an office online again this fall, and am attempting to pick up the shredded pieces of my professional hobbiest's tech stack.

In my pursuit of a more-efficient set of systems, I migrated away from Jenkins towards something called "[Laminar](https://laminar.ohwg.net/)", which has far fewer dependencies, uses about 1/20th of the processor resources, and avoids the security risks made possible by Jenkin's tacked-on-after-the-fact authentication system. 

Laminar is significantly easier to configure, and is designed to have the configurations version controlled.

---

You can see the new build system at [build.jakimfett.com](https://build.jakimfett.com/), although I haven't gotten around to doing much more than getting my homelab essentials building, and it'll be a while before I have the time and focus to get any game stuff back online.

---

That said...if you wanted to create a script to setup a workspace, unpack the necessary bits (mod and otherwise), and make a pull request, I can add it to the build server as-is, and the compiled binaries will be a bit more accessible then.

**Comment by bstienen** [comment]
I'm sorry to hear the backstory. Hope things are currently going better, and if not that 2020 will make things better again. Happy new year :-)

Hmm.. I am not so much interested in working on a build system to be honest. My interest in your mod basically stems from the name of your mod (weird, I know, but true). I am currently a PhD student in particle physics and got this weird plan to write a mod that simulates particle collider experiments. Partially as means of outreach, partially as means of giving me something to do outside of work. The mod would boil down to a couple of things, of which colliding entities (which then turn into new entities) is one. Based on a YouTube video that showcased your mod I thought that I could maybe use your code as inspiration or maybe even as basis (properly cited of course!). Getting the code to work on my own machine would then be step one, hence my initial question.

Now, I am just a hobbyist and have not played minecraft in I think 9 years, let alone attempted to create a mod before. I don't have much time, but I am trying to learn how to use Forge. As you can imagine, this is harder than I imagined beforehand (yay for lack of tutorials).

I think the best thing to do for me is to finish this learning process first and then come back to your code. If somewhere in this process I will learn how to use a build system like you mentioned, I will definitely come back to this issue and give it a go!

**Comment by jakimfett** [comment]
Happy new year to you as well, @bstienen.

The Minecraft years were, despite my health struggles, a net win for me.  
My health struggled, and the developer and larger community has deep-rooted toxicity that ensure that I'll never go back...  
...but I've also gained a lot of technical skills (eg, build systems) that have helped me greatly, and the experience of working with a small online community is one that I will never regret.

I am excited about this because one of the high points, for me, was when Minechem became part of the MinecraftEdu program, and I've always regretted that this system didn't get further developed.

---
**Here's the bad news.**

You're going to run into a lot of frustration learning Java, and Forge, and to be perfectly honest any of the Minecraft modding paradigms are really horrible (despite what is possible with the Spigot server). If you're not already specializing in programming, you'll need to spend a year or so to figure out the topic of "basic modding in minecraft". Even just getting a running development environment is tortorously convoluted, especially if you're working with less-than-current hardware.

Speaking from [personal experience here](http://jakimfett.com/status-report/netbeans-forge-gradle/).

**There is, however, good news too!**  
Instead of Minecraft, try [modding with MineTest](https://dev.minetest.net/Modding_Intro).

With MineTest, you'll get a lot more result for your effort than you would with Minecraft.
For example, the developers of the core engine have made changes because a mod needed access to or capabilities for specific things, vs technically modding Minecraft is still technically illegal (because the middleware that makes it possible for you to write a mod relies on reverse engineering Mojang's obfuscation of the publicly available binaries).
